allow-flight=false
allow-nether=true
difficulty=normal
enable-command-block=true
gamemode=survival
hardcore=false
level-name=world
max-players=20
motd=§aБратский сервер на Paper §6[1.20.1]§r
online-mode=false
pvp=true
server-port=25565
spawn-protection=5
view-distance=10
allow-end=true
enforce-secure-profile=false
