# Основные настройки твоего сервера
allow-flight=false
allow-nether=true
difficulty=normal
enable-command-block=false
gamemode=survival
hardcore=false
max-players=20
motd=§aБратский сервер с Create §6[1.20.1]§r
online-mode=true
pvp=true
server-port=25565
spawn-protection=5
view-distance=10
max-tick-time=60000
enable-jmx-monitoring=false
sync-chunk-writes=true
enforce-secure-profile=false
